version: '3.9'

services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  storygen:
    build: .
    depends_on:
      - ollama
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  ollama_data: