version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH_DISABLED=true  # Disable authentication for simplicity
    depends_on:
      - ollama
    volumes:
      - openwebui_data:/app/backend/data

volumes:
  ollama_data:
  openwebui_data: