version: '3.8'

services:
  cot-mapping-api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: cot-mapping-api
    ports:
      - "8000:8000"
    volumes:
      - ../uploads:/app/uploads
      - ../backups:/app/backups
      - ../logs:/app/logs
      - ../cot_mappings.db:/app/cot_mappings.db
    environment:
      - DATABASE_URL=sqlite:///./cot_mappings.db
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - cot-network

  ollama:
    image: ollama/ollama:latest
    container_name: cot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - cot-network
    # Automatically pull the model on startup
    command: |
      sh -c "
        ollama serve &
        sleep 10 &&
        ollama pull llama3.1:8b &&
        wait
      "

  n8n:
    image: n8nio/n8n:latest
    container_name: cot-n8n
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - ../n8n-workflows:/workflows
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=http://cot-mapping-api:8000
    depends_on:
      - cot-mapping-api
    restart: unless-stopped
    networks:
      - cot-network

volumes:
  ollama_data:
  n8n_data:

networks:
  cot-network:
    driver: bridge