version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  article-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: article-scraper
    ports:
      - "8501:8501"
    volumes:
      - ./articles:/app/articles
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data: 