version: "3.9"

services:
  rest-api:
    build:
      context: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./docs:/app/docs
      - ./vectorstore:/app/vectorstore
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1

  graphql-api:
    build:
      context: .
    command: uvicorn graphql_api:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"
    volumes:
      - ./docs:/app/docs
      - ./vectorstore:/app/vectorstore
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1